baseURL = 'https://skewy.github.io'
languageCode = 'en-us'
title = 'Anti eavesdropping'
theme = "hugo-theme-notrack-master"
newContentEditor = "nvim"
mainSections = ["log"]
# disqusShortname = "example"
paginate = 4


[params]
  author = "Skewy"
  siteHeading = "Skewy - anti eavesdropping" # defaults to author
  favicon = "/img/PlayStoreIcon.png" # Adds a small icon next to the page title in a tab
  showBlogLatest = true
  mainSections = ["blog"]
  showTaxonomyLinks = false
  nBlogLatest = 4 # number of blog post om the home page
  blogLatestHeading = "My writing"
  footer = "Created with the 'No-track' theme from gevhaz (GNU General Public License v3.0). This includes icons and other design elements from the theme. Original content - all rights reserved."
  logosrc = "/img/PlayStoreIcon.png"
  

  [params.social]
    playstore = "Skewy"

[taxonomies]
  year = "year"
  month = "month"
  tags = "tags"
  categories = "categories"

[permalinks]
  blog = "/blog/:year/:month/:slug"

